export { Header } from './header/header.tsx'
export { Footer } from './footer/footer.tsx'
export { Hero } from './hero/hero.tsx'
export { Activities } from './activities/activities.tsx'
export { Testimonials } from './testimonials/testimonials.tsx'
